### ISSUE TITLE
options.scopes is undefined

### ISSUE THREAD

**Issue by keremkurtulus** [gentritabazi01/typeorm-simple-query-parser#3]
After I updated from 1.0.13 to 1.0.15, I encountered this error

`TypeError: Cannot read property 'findIndex' of undefined\n    at /app/node_modules/typeorm-simple-query-parser/lib/MainRepository.js:65:55\n    at Array.forEach (<anonymous>)\n    at UserRepository.applyResourceOptions (/app/node_modules/typeorm-simple-query-parser/lib/MainRepository.js:58:31)\n    at UserRepository.getManyAndCount (/app/node_modules/typeorm-simple-query-parser/lib/MainRepository.js:22:14)\n    at UserService.<anonymous> (/app/src/api/services/Users/UserService.ts:14:38)\n    at Generator.next (<anonymous>)\n    at /app/src/api/services/Users/UserService.ts:20:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/src/api/services/Users/UserService.ts:16:12)\n    at UserService.getAll (/app/src/api/services/Users/UserService.ts:37:16)`

The suggested solution is that check if the `options.scopes` array exists before the iteration.
https://github.com/gentritabazi01/typeorm-simple-query-parser/blob/6bdb3a17ed63d54b6f174d40dfaa4d8f28764721/src/MainRepository.ts#L85

My temporary solution is adding this lines
```
// @ts-ignore
resourceOptions.scopes = [];
...
repository.getManyAndCount(resourceOptions)
```

**Comment by gentritabazi** [comment]
Hi thanks for report.

It's fixed now #4:
